### ISSUE TITLE
coalaize

### ISSUE THREAD

**Issue by sils1297** [hypothesist/coala-vim#1]
hey, does this work? Can we make it official?

**Comment by hypothesist** [comment]
I'll let you know the minute I finish it :)

**Comment by sils1297** [comment]
heh cool :)

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-02 16:18 GMT+01:00 Adhityaa Chandrasekar <notifications@github.com>:

**Comment by hypothesist** [comment]
It's ready! :)
